// Pre-defined theme configurations for the portfolio
// Each theme has both light and dark variants

export const themePresets = {
    'vs-code-dark': {
        name: 'VS Code Dark',
        slug: 'vs-code-dark',
        description: 'Classic VS Code dark theme with cyan and purple accents',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0d1117',
                    secondary: '#0a1929',
                    tertiary: '#080a0e',
                    surface: '#1e1433',
                    elevated: '#1a0f2e',
                    hover: '#1e3a5f',
                },
                text: {
                    primary: '#e5e7eb',
                    secondary: '#cbd5e1',
                    tertiary: '#94a3b8',
                    muted: '#64748b',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#22d3ee',
                    cyanBright: '#00ffff',
                    purple: '#c084fc',
                    purpleDark: '#7c3aed',
                    purpleDarker: '#4c1d95',
                    pink: '#ec4899',
                    pinkBright: '#f472b6',
                    pinkHot: '#ff0080',
                    orange: '#f97316',
                    orangeBright: '#ff9500',
                },
                borders: {
                    primary: '#1e293b',
                    secondary: '#374151',
                    accent: '#4c1d95',
                    cyan: '#22d3ee',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#a78bfa',
                    keyword: '#d946ef',
                    control: '#ff0080',
                    function: '#00ffff',
                    class: '#c084fc',
                    string: '#00ff88',
                    number: '#ff9500',
                    variable: '#a5f3fc',
                    property: '#38bdf8',
                    operator: '#a855f7',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(34, 211, 238, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(34, 211, 238, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ffffff',
                    secondary: '#f8fafc',
                    tertiary: '#f1f5f9',
                    surface: '#e2e8f0',
                    elevated: '#f0f4f8',
                    hover: '#dbeafe',
                },
                text: {
                    primary: '#1e293b',
                    secondary: '#475569',
                    tertiary: '#64748b',
                    muted: '#94a3b8',
                    bright: '#0f172a',
                },
                accents: {
                    cyan: '#0891b2',
                    cyanBright: '#0284c7',
                    purple: '#7c3aed',
                    purpleDark: '#6d28d9',
                    purpleDarker: '#5b21b6',
                    pink: '#db2777',
                    pinkBright: '#ec4899',
                    pinkHot: '#be185d',
                    orange: '#ea580c',
                    orangeBright: '#f97316',
                },
                borders: {
                    primary: '#e2e8f0',
                    secondary: '#cbd5e1',
                    accent: '#c084fc',
                    cyan: '#22d3ee',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#7c3aed',
                    keyword: '#be185d',
                    control: '#be0077',
                    function: '#0891b2',
                    class: '#7c3aed',
                    string: '#059669',
                    number: '#ea580c',
                    variable: '#0e7490',
                    property: '#0284c7',
                    operator: '#7c3aed',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(14, 165, 233, 0.2)',
                },
                overlays: {
                    bg: 'rgba(15, 23, 42, 0.4)',
                    hover: 'rgba(14, 165, 233, 0.1)',
                },
            },
        },
    },

    'ocean-blue': {
        name: 'Ocean Blue',
        slug: 'ocean-blue',
        description: 'Calming ocean-inspired blue palette',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a1628',
                    secondary: '#0f1e36',
                    tertiary: '#051020',
                    surface: '#1a2942',
                    elevated: '#152138',
                    hover: '#1e3a5f',
                },
                text: {
                    primary: '#e0f2fe',
                    secondary: '#bae6fd',
                    tertiary: '#7dd3fc',
                    muted: '#38bdf8',
                    bright: '#f0f9ff',
                },
                accents: {
                    cyan: '#06b6d4',
                    cyanBright: '#22d3ee',
                    purple: '#0ea5e9',
                    purpleDark: '#0284c7',
                    purpleDarker: '#0369a1',
                    pink: '#38bdf8',
                    pinkBright: '#7dd3fc',
                    pinkHot: '#0891b2',
                    orange: '#0ea5e9',
                    orangeBright: '#38bdf8',
                },
                borders: {
                    primary: '#1e3a5f',
                    secondary: '#2563eb',
                    accent: '#0ea5e9',
                    cyan: '#06b6d4',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#06b6d4',
                },
                syntax: {
                    comment: '#7dd3fc',
                    keyword: '#22d3ee',
                    control: '#0ea5e9',
                    function: '#38bdf8',
                    class: '#0284c7',
                    string: '#5eead4',
                    number: '#fbbf24',
                    variable: '#bae6fd',
                    property: '#0891b2',
                    operator: '#0ea5e9',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(6, 182, 212, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(6, 182, 212, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#f0f9ff',
                    secondary: '#e0f2fe',
                    tertiary: '#bae6fd',
                    surface: '#d1e9f6',
                    elevated: '#e8f5fa',
                    hover: '#bae6fd',
                },
                text: {
                    primary: '#0c4a6e',
                    secondary: '#075985',
                    tertiary: '#0369a1',
                    muted: '#0891b2',
                    bright: '#082f49',
                },
                accents: {
                    cyan: '#0891b2',
                    cyanBright: '#06b6d4',
                    purple: '#0284c7',
                    purpleDark: '#0369a1',
                    purpleDarker: '#075985',
                    pink: '#0ea5e9',
                    pinkBright: '#38bdf8',
                    pinkHot: '#0284c7',
                    orange: '#0891b2',
                    orangeBright: '#06b6d4',
                },
                borders: {
                    primary: '#bae6fd',
                    secondary: '#7dd3fc',
                    accent: '#0ea5e9',
                    cyan: '#06b6d4',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#0891b2',
                    keyword: '#0284c7',
                    control: '#0369a1',
                    function: '#0ea5e9',
                    class: '#0284c7',
                    string: '#059669',
                    number: '#ea580c',
                    variable: '#0c4a6e',
                    property: '#0891b2',
                    operator: '#0284c7',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(6, 182, 212, 0.2)',
                },
                overlays: {
                    bg: 'rgba(8, 145, 178, 0.4)',
                    hover: 'rgba(6, 182, 212, 0.1)',
                },
            },
        },
    },

    'forest-green': {
        name: 'Forest Green',
        slug: 'forest-green',
        description: 'Natural earthy green tones',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a1f0f',
                    secondary: '#0f2817',
                    tertiary: '#051008',
                    surface: '#1a3323',
                    elevated: '#152b1e',
                    hover: '#1e4d2b',
                },
                text: {
                    primary: '#d1fae5',
                    secondary: '#a7f3d0',
                    tertiary: '#6ee7b7',
                    muted: '#34d399',
                    bright: '#ecfdf5',
                },
                accents: {
                    cyan: '#10b981',
                    cyanBright: '#34d399',
                    purple: '#059669',
                    purpleDark: '#047857',
                    purpleDarker: '#065f46',
                    pink: '#6ee7b7',
                    pinkBright: '#a7f3d0',
                    pinkHot: '#059669',
                    orange: '#84cc16',
                    orangeBright: '#a3e635',
                },
                borders: {
                    primary: '#1e4d2b',
                    secondary: '#166534',
                    accent: '#10b981',
                    cyan: '#34d399',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#6ee7b7',
                    keyword: '#34d399',
                    control: '#10b981',
                    function: '#a7f3d0',
                    class: '#059669',
                    string: '#d1fae5',
                    number: '#fbbf24',
                    variable: '#a7f3d0',
                    property: '#34d399',
                    operator: '#10b981',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(16, 185, 129, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(16, 185, 129, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ecfdf5',
                    secondary: '#d1fae5',
                    tertiary: '#a7f3d0',
                    surface: '#d4f4dd',
                    elevated: '#e8f8ec',
                    hover: '#a7f3d0',
                },
                text: {
                    primary: '#064e3b',
                    secondary: '#065f46',
                    tertiary: '#047857',
                    muted: '#059669',
                    bright: '#022c22',
                },
                accents: {
                    cyan: '#059669',
                    cyanBright: '#10b981',
                    purple: '#047857',
                    purpleDark: '#065f46',
                    purpleDarker: '#064e3b',
                    pink: '#10b981',
                    pinkBright: '#34d399',
                    pinkHot: '#047857',
                    orange: '#65a30d',
                    orangeBright: '#84cc16',
                },
                borders: {
                    primary: '#a7f3d0',
                    secondary: '#6ee7b7',
                    accent: '#10b981',
                    cyan: '#34d399',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#059669',
                    keyword: '#047857',
                    control: '#065f46',
                    function: '#10b981',
                    class: '#047857',
                    string: '#064e3b',
                    number: '#ea580c',
                    variable: '#065f46',
                    property: '#059669',
                    operator: '#047857',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(16, 185, 129, 0.2)',
                },
                overlays: {
                    bg: 'rgba(5, 150, 105, 0.4)',
                    hover: 'rgba(16, 185, 129, 0.1)',
                },
            },
        },
    },

    'sunset-orange': {
        name: 'Sunset Orange',
        slug: 'sunset-orange',
        description: 'Warm sunset-inspired orange and red tones',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#1f0a0a',
                    secondary: '#2d1111',
                    tertiary: '#150505',
                    surface: '#3d1a1a',
                    elevated: '#331414',
                    hover: '#4d2020',
                },
                text: {
                    primary: '#fed7aa',
                    secondary: '#fdba74',
                    tertiary: '#fb923c',
                    muted: '#f97316',
                    bright: '#fff7ed',
                },
                accents: {
                    cyan: '#f97316',
                    cyanBright: '#fb923c',
                    purple: '#ea580c',
                    purpleDark: '#c2410c',
                    purpleDarker: '#9a3412',
                    pink: '#fb923c',
                    pinkBright: '#fdba74',
                    pinkHot: '#ea580c',
                    orange: '#f59e0b',
                    orangeBright: '#fbbf24',
                },
                borders: {
                    primary: '#4d2020',
                    secondary: '#7c2d12',
                    accent: '#f97316',
                    cyan: '#fb923c',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#fdba74',
                    keyword: '#fb923c',
                    control: '#f97316',
                    function: '#fbbf24',
                    class: '#ea580c',
                    string: '#fde047',
                    number: '#fbbf24',
                    variable: '#fed7aa',
                    property: '#fb923c',
                    operator: '#f97316',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(249, 115, 22, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(249, 115, 22, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#fff7ed',
                    secondary: '#ffedd5',
                    tertiary: '#fed7aa',
                    surface: '#fef3e2',
                    elevated: '#fef8f0',
                    hover: '#fed7aa',
                },
                text: {
                    primary: '#7c2d12',
                    secondary: '#9a3412',
                    tertiary: '#c2410c',
                    muted: '#ea580c',
                    bright: '#431407',
                },
                accents: {
                    cyan: '#ea580c',
                    cyanBright: '#f97316',
                    purple: '#c2410c',
                    purpleDark: '#9a3412',
                    purpleDarker: '#7c2d12',
                    pink: '#f97316',
                    pinkBright: '#fb923c',
                    pinkHot: '#c2410c',
                    orange: '#d97706',
                    orangeBright: '#f59e0b',
                },
                borders: {
                    primary: '#fed7aa',
                    secondary: '#fdba74',
                    accent: '#f97316',
                    cyan: '#fb923c',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#ea580c',
                    keyword: '#c2410c',
                    control: '#9a3412',
                    function: '#f97316',
                    class: '#c2410c',
                    string: '#ca8a04',
                    number: '#d97706',
                    variable: '#7c2d12',
                    property: '#ea580c',
                    operator: '#c2410c',
                    punctuation: '#a16207',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(249, 115, 22, 0.2)',
                },
                overlays: {
                    bg: 'rgba(234, 88, 12, 0.4)',
                    hover: 'rgba(249, 115, 22, 0.1)',
                },
            },
        },
    },

    'royal-purple': {
        name: 'Royal Purple',
        slug: 'royal-purple',
        description: 'Elegant purple and magenta theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#1a0a2e',
                    secondary: '#240f3d',
                    tertiary: '#0f051a',
                    surface: '#2e1a4a',
                    elevated: '#261438',
                    hover: '#3d2056',
                },
                text: {
                    primary: '#f3e8ff',
                    secondary: '#e9d5ff',
                    tertiary: '#d8b4fe',
                    muted: '#c084fc',
                    bright: '#faf5ff',
                },
                accents: {
                    cyan: '#a855f7',
                    cyanBright: '#c084fc',
                    purple: '#9333ea',
                    purpleDark: '#7c3aed',
                    purpleDarker: '#6d28d9',
                    pink: '#d946ef',
                    pinkBright: '#e879f9',
                    pinkHot: '#c026d3',
                    orange: '#a855f7',
                    orangeBright: '#c084fc',
                },
                borders: {
                    primary: '#3d2056',
                    secondary: '#6d28d9',
                    accent: '#a855f7',
                    cyan: '#c084fc',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#d8b4fe',
                    keyword: '#c084fc',
                    control: '#a855f7',
                    function: '#e879f9',
                    class: '#9333ea',
                    string: '#fde047',
                    number: '#fbbf24',
                    variable: '#e9d5ff',
                    property: '#c084fc',
                    operator: '#a855f7',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(168, 85, 247, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(168, 85, 247, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#faf5ff',
                    secondary: '#f3e8ff',
                    tertiary: '#e9d5ff',
                    surface: '#f0e7fa',
                    elevated: '#f7f2fa',
                    hover: '#e9d5ff',
                },
                text: {
                    primary: '#581c87',
                    secondary: '#6d28d9',
                    tertiary: '#7c3aed',
                    muted: '#9333ea',
                    bright: '#3b0764',
                },
                accents: {
                    cyan: '#7c3aed',
                    cyanBright: '#9333ea',
                    purple: '#6d28d9',
                    purpleDark: '#5b21b6',
                    purpleDarker: '#581c87',
                    pink: '#c026d3',
                    pinkBright: '#d946ef',
                    pinkHot: '#a21caf',
                    orange: '#7c3aed',
                    orangeBright: '#9333ea',
                },
                borders: {
                    primary: '#e9d5ff',
                    secondary: '#d8b4fe',
                    accent: '#a855f7',
                    cyan: '#c084fc',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#9333ea',
                    keyword: '#7c3aed',
                    control: '#6d28d9',
                    function: '#a855f7',
                    class: '#7c3aed',
                    string: '#ca8a04',
                    number: '#ea580c',
                    variable: '#581c87',
                    property: '#9333ea',
                    operator: '#7c3aed',
                    punctuation: '#a16207',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(168, 85, 247, 0.2)',
                },
                overlays: {
                    bg: 'rgba(124, 58, 237, 0.4)',
                    hover: 'rgba(168, 85, 247, 0.1)',
                },
            },
        },
    },

    'monochrome': {
        name: 'Monochrome',
        slug: 'monochrome',
        description: 'Professional grayscale theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a0a0a',
                    secondary: '#141414',
                    tertiary: '#050505',
                    surface: '#1f1f1f',
                    elevated: '#1a1a1a',
                    hover: '#2a2a2a',
                },
                text: {
                    primary: '#f5f5f5',
                    secondary: '#e5e5e5',
                    tertiary: '#d4d4d4',
                    muted: '#a3a3a3',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#d4d4d4',
                    cyanBright: '#e5e5e5',
                    purple: '#a3a3a3',
                    purpleDark: '#8a8a8a',
                    purpleDarker: '#737373',
                    pink: '#d4d4d4',
                    pinkBright: '#e5e5e5',
                    pinkHot: '#a3a3a3',
                    orange: '#d4d4d4',
                    orangeBright: '#e5e5e5',
                },
                borders: {
                    primary: '#2a2a2a',
                    secondary: '#3f3f46',
                    accent: '#a3a3a3',
                    cyan: '#d4d4d4',
                },
                status: {
                    error: '#ef4444',
                    warning: '#f59e0b',
                    success: '#22c55e',
                    info: '#3b82f6',
                },
                syntax: {
                    comment: '#a3a3a3',
                    keyword: '#e5e5e5',
                    control: '#d4d4d4',
                    function: '#f5f5f5',
                    class: '#e5e5e5',
                    string: '#d4d4d4',
                    number: '#a3a3a3',
                    variable: '#e5e5e5',
                    property: '#d4d4d4',
                    operator: '#a3a3a3',
                    punctuation: '#8a8a8a',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(212, 212, 212, 0.1)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(212, 212, 212, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ffffff',
                    secondary: '#fafafa',
                    tertiary: '#f5f5f5',
                    surface: '#e5e5e5',
                    elevated: '#f0f0f0',
                    hover: '#e5e5e5',
                },
                text: {
                    primary: '#0a0a0a',
                    secondary: '#262626',
                    tertiary: '#404040',
                    muted: '#737373',
                    bright: '#000000',
                },
                accents: {
                    cyan: '#404040',
                    cyanBright: '#262626',
                    purple: '#737373',
                    purpleDark: '#525252',
                    purpleDarker: '#404040',
                    pink: '#404040',
                    pinkBright: '#262626',
                    pinkHot: '#525252',
                    orange: '#404040',
                    orangeBright: '#262626',
                },
                borders: {
                    primary: '#e5e5e5',
                    secondary: '#d4d4d4',
                    accent: '#737373',
                    cyan: '#404040',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#16a34a',
                    info: '#2563eb',
                },
                syntax: {
                    comment: '#737373',
                    keyword: '#262626',
                    control: '#404040',
                    function: '#0a0a0a',
                    class: '#262626',
                    string: '#404040',
                    number: '#737373',
                    variable: '#262626',
                    property: '#404040',
                    operator: '#737373',
                    punctuation: '#a3a3a3',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(64, 64, 64, 0.1)',
                },
                overlays: {
                    bg: 'rgba(10, 10, 10, 0.4)',
                    hover: 'rgba(64, 64, 64, 0.1)',
                },
            },
        },
    },

    'dracula': {
        name: 'Dracula',
        slug: 'dracula',
        description: 'Vampire-themed color palette',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#282a36',
                    secondary: '#44475a',
                    tertiary: '#21222c',
                    surface: '#6272a4',
                    elevated: '#44475a',
                    hover: '#6272a4',
                },
                text: {
                    primary: '#f8f8f2',
                    secondary: '#bfbfbf',
                    tertiary: '#6272a4',
                    muted: '#6272a4',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#8be9fd',
                    cyanBright: '#a4ffff',
                    purple: '#bd93f9',
                    purpleDark: '#6272a4',
                    purpleDarker: '#44475a',
                    pink: '#ff79c6',
                    pinkBright: '#ff92d0',
                    pinkHot: '#ff5555',
                    orange: '#ffb86c',
                    orangeBright: '#ffca85',
                },
                borders: {
                    primary: '#6272a4',
                    secondary: '#44475a',
                    accent: '#bd93f9',
                    cyan: '#8be9fd',
                },
                status: {
                    error: '#ff5555',
                    warning: '#f1fa8c',
                    success: '#50fa7b',
                    info: '#8be9fd',
                },
                syntax: {
                    comment: '#6272a4',
                    keyword: '#ff79c6',
                    control: '#ff79c6',
                    function: '#50fa7b',
                    class: '#8be9fd',
                    string: '#f1fa8c',
                    number: '#bd93f9',
                    variable: '#f8f8f2',
                    property: '#66d9ef',
                    operator: '#ff79c6',
                    punctuation: '#f8f8f2',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(189, 147, 249, 0.3)',
                },
                overlays: {
                    bg: 'rgba(40, 42, 54, 0.6)',
                    hover: 'rgba(189, 147, 249, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#f8f8f2',
                    secondary: '#e2e2e2',
                    tertiary: '#f0f0f0',
                    surface: '#e6e6e6',
                    elevated: '#ffffff',
                    hover: '#e2e2e2',
                },
                text: {
                    primary: '#282a36',
                    secondary: '#44475a',
                    tertiary: '#6272a4',
                    muted: '#999999',
                    bright: '#000000',
                },
                accents: {
                    cyan: '#00b7ff',
                    cyanBright: '#8be9fd',
                    purple: '#9558ea',
                    purpleDark: '#5e389e',
                    purpleDarker: '#3a2266',
                    pink: '#ff5ea7',
                    pinkBright: '#ff79c6',
                    pinkHot: '#e01616',
                    orange: '#e68b30',
                    orangeBright: '#ffb86c',
                },
                borders: {
                    primary: '#bfbfbf',
                    secondary: '#d9d9d9',
                    accent: '#bd93f9',
                    cyan: '#8be9fd',
                },
                status: {
                    error: '#ff5555',
                    warning: '#f1fa8c',
                    success: '#50fa7b',
                    info: '#8be9fd',
                },
                syntax: {
                    comment: '#6272a4',
                    keyword: '#ff79c6',
                    control: '#ff79c6',
                    function: '#50fa7b',
                    class: '#8be9fd',
                    string: '#f1fa8c',
                    number: '#bd93f9',
                    variable: '#282a36',
                    property: '#66d9ef',
                    operator: '#ff79c6',
                    punctuation: '#44475a',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(189, 147, 249, 0.2)',
                },
                overlays: {
                    bg: 'rgba(248, 248, 242, 0.5)',
                    hover: 'rgba(189, 147, 249, 0.1)',
                },
            },
        },
    },

    'nord': {
        name: 'Nord',
        slug: 'nord',
        description: 'Arctic, north-bluish color palette',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#2e3440',
                    secondary: '#3b4252',
                    tertiary: '#242933',
                    surface: '#434c5e',
                    elevated: '#4c566a',
                    hover: '#434c5e',
                },
                text: {
                    primary: '#eceff4',
                    secondary: '#e5e9f0',
                    tertiary: '#d8dee9',
                    muted: '#4c566a',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#88c0d0',
                    cyanBright: '#8fbcbb',
                    purple: '#b48ead',
                    purpleDark: '#5e81ac',
                    purpleDarker: '#3b4252',
                    pink: '#bf616a',
                    pinkBright: '#d08770',
                    pinkHot: '#bf616a',
                    orange: '#d08770',
                    orangeBright: '#ebcb8b',
                },
                borders: {
                    primary: '#4c566a',
                    secondary: '#434c5e',
                    accent: '#81a1c1',
                    cyan: '#88c0d0',
                },
                status: {
                    error: '#bf616a',
                    warning: '#ebcb8b',
                    success: '#a3be8c',
                    info: '#88c0d0',
                },
                syntax: {
                    comment: '#4c566a',
                    keyword: '#81a1c1',
                    control: '#81a1c1',
                    function: '#88c0d0',
                    class: '#8fbcbb',
                    string: '#a3be8c',
                    number: '#b48ead',
                    variable: '#d8dee9',
                    property: '#88c0d0',
                    operator: '#81a1c1',
                    punctuation: '#eceff4',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(136, 192, 208, 0.2)',
                },
                overlays: {
                    bg: 'rgba(46, 52, 64, 0.6)',
                    hover: 'rgba(136, 192, 208, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#eceff4',
                    secondary: '#e5e9f0',
                    tertiary: '#d8dee9',
                    surface: '#ffffff',
                    elevated: '#ffffff',
                    hover: '#e5e9f0',
                },
                text: {
                    primary: '#2e3440',
                    secondary: '#3b4252',
                    tertiary: '#434c5e',
                    muted: '#999999',
                    bright: '#000000',
                },
                accents: {
                    cyan: '#5e81ac',
                    cyanBright: '#81a1c1',
                    purple: '#b48ead',
                    purpleDark: '#4c566a',
                    purpleDarker: '#2e3440',
                    pink: '#bf616a',
                    pinkBright: '#d08770',
                    pinkHot: '#bf616a',
                    orange: '#c06040',
                    orangeBright: '#d08770',
                },
                borders: {
                    primary: '#d8dee9',
                    secondary: '#e5e9f0',
                    accent: '#81a1c1',
                    cyan: '#5e81ac',
                },
                status: {
                    error: '#bf616a',
                    warning: '#ebcb8b',
                    success: '#a3be8c',
                    info: '#5e81ac',
                },
                syntax: {
                    comment: '#d8dee9',
                    keyword: '#5e81ac',
                    control: '#5e81ac',
                    function: '#81a1c1',
                    class: '#5e81ac',
                    string: '#a3be8c',
                    number: '#b48ead',
                    variable: '#2e3440',
                    property: '#88c0d0',
                    operator: '#5e81ac',
                    punctuation: '#2e3440',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(94, 129, 172, 0.2)',
                },
                overlays: {
                    bg: 'rgba(236, 239, 244, 0.5)',
                    hover: 'rgba(94, 129, 172, 0.1)',
                },
            },
        },
    },

    'cyberpunk': {
        name: 'Cyberpunk',
        slug: 'cyberpunk',
        description: 'Neon-infused high contrast theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#050505',
                    secondary: '#000000',
                    tertiary: '#0a0a0a',
                    surface: '#121212',
                    elevated: '#080808',
                    hover: '#1a1a1a',
                },
                text: {
                    primary: '#fff0f5', // Lavender blush
                    secondary: '#00ffff', // Cyan
                    tertiary: '#ff00ff', // Magenta
                    muted: '#fsee00', // Yellow
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#00ffff',
                    cyanBright: '#ccffff',
                    purple: '#bc13fe',
                    purpleDark: '#8a2be2',
                    purpleDarker: '#4b0082',
                    pink: '#ff0099',
                    pinkBright: '#ff69b4',
                    pinkHot: '#ff0055',
                    orange: '#ffea00',
                    orangeBright: '#ffff00',
                },
                borders: {
                    primary: '#333',
                    secondary: '#00ffff',
                    accent: '#ff0099',
                    cyan: '#00ffff',
                },
                status: {
                    error: '#ff0055',
                    warning: '#ffea00',
                    success: '#00ff99',
                    info: '#00ffff',
                },
                syntax: {
                    comment: '#696969',
                    keyword: '#ff0099',
                    control: '#00ffff',
                    function: '#ffea00',
                    class: '#bc13fe',
                    string: '#00ff99',
                    number: '#ff0055',
                    variable: '#fff0f5',
                    property: '#00ffff',
                    operator: '#ffea00',
                    punctuation: '#ffffff',
                },
                shadows: {
                    sm: '0 0 5px rgba(0, 255, 255, 0.5)',
                    md: '0 0 10px rgba(255, 0, 153, 0.5)',
                    lg: '0 0 20px rgba(255, 234, 0, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.8)',
                    hover: 'rgba(0, 255, 255, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ffffff',
                    secondary: '#f0f0f0',
                    tertiary: '#fafafa',
                    surface: '#e0e0e0',
                    elevated: '#ffffff',
                    hover: '#e0e0e0',
                },
                text: {
                    primary: '#000000',
                    secondary: '#00aaaa',
                    tertiary: '#aa00aa',
                    muted: '#aaaa00',
                    bright: '#111111',
                },
                accents: {
                    cyan: '#00aaaa',
                    cyanBright: '#00ffff',
                    purple: '#800080',
                    purpleDark: '#4b0082',
                    purpleDarker: '#2e004f',
                    pink: '#c71585',
                    pinkBright: '#ff1493',
                    pinkHot: '#ff0000',
                    orange: '#ffae00',
                    orangeBright: '#ffcc00',
                },
                borders: {
                    primary: '#dcdcdc',
                    secondary: '#00aaaa',
                    accent: '#c71585',
                    cyan: '#00aaaa',
                },
                status: {
                    error: '#dc143c',
                    warning: '#ffae00',
                    success: '#00aa00',
                    info: '#00aaaa',
                },
                syntax: {
                    comment: '#808080',
                    keyword: '#c71585',
                    control: '#00aaaa',
                    function: '#aaaa00',
                    class: '#800080',
                    string: '#00aa00',
                    number: '#dc143c',
                    variable: '#000000',
                    property: '#00aaaa',
                    operator: '#aaaa00',
                    punctuation: '#000000',
                },
                shadows: {
                    sm: '0 0 2px rgba(0, 0, 0, 0.3)',
                    md: '0 0 5px rgba(0, 0, 0, 0.2)',
                    lg: '0 0 10px rgba(0, 0, 0, 0.1)',
                },
                overlays: {
                    bg: 'rgba(255, 255, 255, 0.6)',
                    hover: 'rgba(0, 170, 170, 0.1)',
                },
            },
        },
    },

    'gruvbox': {
        name: 'Gruvbox',
        slug: 'gruvbox',
        description: 'Retro groove color scheme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#282828',
                    secondary: '#3c3836',
                    tertiary: '#1d2021',
                    surface: '#504945',
                    elevated: '#32302f',
                    hover: '#504945',
                },
                text: {
                    primary: '#ebdbb2',
                    secondary: '#a89984',
                    tertiary: '#928374',
                    muted: '#7c6f64',
                    bright: '#fbf1c7',
                },
                accents: {
                    cyan: '#8ec07c',
                    cyanBright: '#b8bb26',
                    purple: '#d3869b',
                    purpleDark: '#b16286',
                    purpleDarker: '#8f3f71',
                    pink: '#fb4934',
                    pinkBright: '#d3869b',
                    pinkHot: '#cc241d',
                    orange: '#fe8019',
                    orangeBright: '#fabd2f',
                },
                borders: {
                    primary: '#504945',
                    secondary: '#3c3836',
                    accent: '#fe8019',
                    cyan: '#8ec07c',
                },
                status: {
                    error: '#cc241d',
                    warning: '#d79921',
                    success: '#98971a',
                    info: '#458588',
                },
                syntax: {
                    comment: '#928374',
                    keyword: '#fb4934',
                    control: '#fb4934',
                    function: '#b8bb26',
                    class: '#fabd2f',
                    string: '#b8bb26',
                    number: '#d3869b',
                    variable: '#ebdbb2',
                    property: '#8ec07c',
                    operator: '#fe8019',
                    punctuation: '#ebdbb2',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(254, 128, 25, 0.3)',
                },
                overlays: {
                    bg: 'rgba(40, 40, 40, 0.6)',
                    hover: 'rgba(254, 128, 25, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#fbf1c7',
                    secondary: '#ebdbb2',
                    tertiary: '#f9f5d7',
                    surface: '#d5c4a1',
                    elevated: '#f2e5bc',
                    hover: '#d5c4a1',
                },
                text: {
                    primary: '#3c3836',
                    secondary: '#504945',
                    tertiary: '#665c54',
                    muted: '#7c6f64',
                    bright: '#282828',
                },
                accents: {
                    cyan: '#427b58',
                    cyanBright: '#689d6a',
                    purple: '#8f3f71',
                    purpleDark: '#b16286',
                    purpleDarker: '#d3869b',
                    pink: '#cc241d',
                    pinkBright: '#9d0006',
                    pinkHot: '#fb4934',
                    orange: '#d65d0e',
                    orangeBright: '#fe8019',
                },
                borders: {
                    primary: '#bdae93',
                    secondary: '#d5c4a1',
                    accent: '#af3a03',
                    cyan: '#427b58',
                },
                status: {
                    error: '#cc241d',
                    warning: '#d79921',
                    success: '#98971a',
                    info: '#458588',
                },
                syntax: {
                    comment: '#928374',
                    keyword: '#9d0006',
                    control: '#9d0006',
                    function: '#79740e',
                    class: '#b57614',
                    string: '#79740e',
                    number: '#8f3f71',
                    variable: '#3c3836',
                    property: '#427b58',
                    operator: '#af3a03',
                    punctuation: '#3c3836',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(175, 58, 3, 0.2)',
                },
                overlays: {
                    bg: 'rgba(251, 241, 199, 0.5)',
                    hover: 'rgba(175, 58, 3, 0.1)',
                },
            },
        },
    },

    'solarized': {
        name: 'Solarized',
        slug: 'solarized',
        description: 'Precision low-contrast color palette',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#002b36',
                    secondary: '#073642',
                    tertiary: '#00212b',
                    surface: '#586e75',
                    elevated: '#073642',
                    hover: '#586e75',
                },
                text: {
                    primary: '#839496',
                    secondary: '#93a1a1',
                    tertiary: '#586e75',
                    muted: '#657b83',
                    bright: '#fdf6e3',
                },
                accents: {
                    cyan: '#2aa198',
                    cyanBright: '#2aa198',
                    purple: '#6c71c4',
                    purpleDark: '#268bd2',
                    purpleDarker: '#268bd2',
                    pink: '#d33682',
                    pinkBright: '#d33682',
                    pinkHot: '#dc322f',
                    orange: '#cb4b16',
                    orangeBright: '#b58900',
                },
                borders: {
                    primary: '#586e75',
                    secondary: '#073642',
                    accent: '#2aa198',
                    cyan: '#2aa198',
                },
                status: {
                    error: '#dc322f',
                    warning: '#b58900',
                    success: '#859900',
                    info: '#268bd2',
                },
                syntax: {
                    comment: '#586e75',
                    keyword: '#859900',
                    control: '#859900',
                    function: '#268bd2',
                    class: '#b58900',
                    string: '#2aa198',
                    number: '#d33682',
                    variable: '#839496',
                    property: '#268bd2',
                    operator: '#859900',
                    punctuation: '#839496',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(42, 161, 152, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 43, 54, 0.6)',
                    hover: 'rgba(42, 161, 152, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#fdf6e3',
                    secondary: '#eee8d5',
                    tertiary: '#fdf6e3',
                    surface: '#93a1a1',
                    elevated: '#eee8d5',
                    hover: '#93a1a1',
                },
                text: {
                    primary: '#657b83',
                    secondary: '#586e75',
                    tertiary: '#93a1a1',
                    muted: '#839496',
                    bright: '#002b36',
                },
                accents: {
                    cyan: '#2aa198',
                    cyanBright: '#2aa198',
                    purple: '#6c71c4',
                    purpleDark: '#268bd2',
                    purpleDarker: '#268bd2',
                    pink: '#d33682',
                    pinkBright: '#d33682',
                    pinkHot: '#dc322f',
                    orange: '#cb4b16',
                    orangeBright: '#b58900',
                },
                borders: {
                    primary: '#93a1a1',
                    secondary: '#eee8d5',
                    accent: '#2aa198',
                    cyan: '#2aa198',
                },
                status: {
                    error: '#dc322f',
                    warning: '#b58900',
                    success: '#859900',
                    info: '#268bd2',
                },
                syntax: {
                    comment: '#93a1a1',
                    keyword: '#859900',
                    control: '#859900',
                    function: '#268bd2',
                    class: '#b58900',
                    string: '#2aa198',
                    number: '#d33682',
                    variable: '#657b83',
                    property: '#268bd2',
                    operator: '#859900',
                    punctuation: '#657b83',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(42, 161, 152, 0.2)',
                },
                overlays: {
                    bg: 'rgba(253, 246, 227, 0.5)',
                    hover: 'rgba(42, 161, 152, 0.1)',
                },
            },
        },
    },

    'catppuccin': {
        name: 'Catppuccin',
        slug: 'catppuccin',
        description: 'Soothing pastel theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: { // Macchiato
                backgrounds: {
                    primary: '#24273a',
                    secondary: '#1e2030',
                    tertiary: '#181926',
                    surface: '#363a4f',
                    elevated: '#1e2030',
                    hover: '#363a4f',
                },
                text: {
                    primary: '#cad3f5',
                    secondary: '#a5adcb',
                    tertiary: '#939ab7',
                    muted: '#8087a2',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#8aadf4', // Blue
                    cyanBright: '#8bd5ca', // Teal
                    purple: '#c6a0f6', // Mauve
                    purpleDark: '#b7bdf8', // Lavender
                    purpleDarker: '#8aadf4', // Blue
                    pink: '#f5bde6', // Pink
                    pinkBright: '#f4dbd6', // Rosewater
                    pinkHot: '#ee99a0', // Maroon
                    orange: '#f5a97f', // Peach
                    orangeBright: '#eed49f', // Yellow
                },
                borders: {
                    primary: '#494d64',
                    secondary: '#363a4f',
                    accent: '#8aadf4',
                    cyan: '#8bd5ca',
                },
                status: {
                    error: '#ed8796', // Red
                    warning: '#eed49f', // Yellow
                    success: '#a6da95', // Green
                    info: '#8aadf4', // Blue
                },
                syntax: {
                    comment: '#5b6078',
                    keyword: '#c6a0f6',
                    control: '#c6a0f6',
                    function: '#8aadf4',
                    class: '#eed49f',
                    string: '#a6da95',
                    number: '#f5a97f',
                    variable: '#cad3f5',
                    property: '#8aadf4',
                    operator: '#8bd5ca',
                    punctuation: '#cad3f5',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(138, 173, 244, 0.3)',
                },
                overlays: {
                    bg: 'rgba(36, 39, 58, 0.6)',
                    hover: 'rgba(138, 173, 244, 0.15)',
                },
            },
            light: { // Latte
                backgrounds: {
                    primary: '#eff1f5',
                    secondary: '#e6e9ef',
                    tertiary: '#dce0e8',
                    surface: '#ccd0da',
                    elevated: '#e6e9ef',
                    hover: '#ccd0da',
                },
                text: {
                    primary: '#4c4f69',
                    secondary: '#5c5f77',
                    tertiary: '#6c6f85',
                    muted: '#7c7f93',
                    bright: '#202124',
                },
                accents: {
                    cyan: '#1e66f5', // Blue
                    cyanBright: '#179299', // Teal
                    purple: '#8839ef', // Mauve
                    purpleDark: '#7287fd', // Lavender
                    purpleDarker: '#1e66f5', // Blue
                    pink: '#ea76cb', // Pink
                    pinkBright: '#dc8a78', // Rosewater
                    pinkHot: '#e64553', // Maroon
                    orange: '#fe640b', // Peach
                    orangeBright: '#df8e1d', // Yellow
                },
                borders: {
                    primary: '#bcc0cc',
                    secondary: '#ccd0da',
                    accent: '#1e66f5',
                    cyan: '#179299',
                },
                status: {
                    error: '#d20f39', // Red
                    warning: '#df8e1d', // Yellow
                    success: '#40a02b', // Green
                    info: '#1e66f5', // Blue
                },
                syntax: {
                    comment: '#acb0be',
                    keyword: '#8839ef',
                    control: '#8839ef',
                    function: '#1e66f5',
                    class: '#df8e1d',
                    string: '#40a02b',
                    number: '#fe640b',
                    variable: '#4c4f69',
                    property: '#1e66f5',
                    operator: '#179299',
                    punctuation: '#4c4f69',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(30, 102, 245, 0.2)',
                },
                overlays: {
                    bg: 'rgba(239, 241, 245, 0.5)',
                    hover: 'rgba(30, 102, 245, 0.1)',
                },
            },
        },
    },
};

// Helper function to get all theme names
export const getThemeNames = () => Object.keys(themePresets);

// Helper function to get a specific theme
export const getTheme = (slug) => themePresets[slug];

// Helper function to check if a theme is predefined
export const isPredefinedTheme = (slug) => !!themePresets[slug];
