// Pre-defined theme configurations for the portfolio
// Each theme has both light and dark variants

export const themePresets = {
    'vs-code-dark': {
        name: 'VS Code Dark',
        slug: 'vs-code-dark',
        description: 'Classic VS Code dark theme with cyan and purple accents',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0d1117',
                    secondary: '#0a1929',
                    tertiary: '#080a0e',
                    surface: '#1e1433',
                    elevated: '#1a0f2e',
                    hover: '#1e3a5f',
                },
                text: {
                    primary: '#e5e7eb',
                    secondary: '#cbd5e1',
                    tertiary: '#94a3b8',
                    muted: '#64748b',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#22d3ee',
                    cyanBright: '#00ffff',
                    purple: '#c084fc',
                    purpleDark: '#7c3aed',
                    purpleDarker: '#4c1d95',
                    pink: '#ec4899',
                    pinkBright: '#f472b6',
                    pinkHot: '#ff0080',
                    orange: '#f97316',
                    orangeBright: '#ff9500',
                },
                borders: {
                    primary: '#1e293b',
                    secondary: '#374151',
                    accent: '#4c1d95',
                    cyan: '#22d3ee',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#a78bfa',
                    keyword: '#d946ef',
                    control: '#ff0080',
                    function: '#00ffff',
                    class: '#c084fc',
                    string: '#00ff88',
                    number: '#ff9500',
                    variable: '#a5f3fc',
                    property: '#38bdf8',
                    operator: '#a855f7',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(34, 211, 238, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(34, 211, 238, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ffffff',
                    secondary: '#f8fafc',
                    tertiary: '#f1f5f9',
                    surface: '#e2e8f0',
                    elevated: '#f0f4f8',
                    hover: '#dbeafe',
                },
                text: {
                    primary: '#1e293b',
                    secondary: '#475569',
                    tertiary: '#64748b',
                    muted: '#94a3b8',
                    bright: '#0f172a',
                },
                accents: {
                    cyan: '#0891b2',
                    cyanBright: '#0284c7',
                    purple: '#7c3aed',
                    purpleDark: '#6d28d9',
                    purpleDarker: '#5b21b6',
                    pink: '#db2777',
                    pinkBright: '#ec4899',
                    pinkHot: '#be185d',
                    orange: '#ea580c',
                    orangeBright: '#f97316',
                },
                borders: {
                    primary: '#e2e8f0',
                    secondary: '#cbd5e1',
                    accent: '#c084fc',
                    cyan: '#22d3ee',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#7c3aed',
                    keyword: '#be185d',
                    control: '#be0077',
                    function: '#0891b2',
                    class: '#7c3aed',
                    string: '#059669',
                    number: '#ea580c',
                    variable: '#0e7490',
                    property: '#0284c7',
                    operator: '#7c3aed',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(14, 165, 233, 0.2)',
                },
                overlays: {
                    bg: 'rgba(15, 23, 42, 0.4)',
                    hover: 'rgba(14, 165, 233, 0.1)',
                },
            },
        },
    },

    'ocean-blue': {
        name: 'Ocean Blue',
        slug: 'ocean-blue',
        description: 'Calming ocean-inspired blue palette',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a1628',
                    secondary: '#0f1e36',
                    tertiary: '#051020',
                    surface: '#1a2942',
                    elevated: '#152138',
                    hover: '#1e3a5f',
                },
                text: {
                    primary: '#e0f2fe',
                    secondary: '#bae6fd',
                    tertiary: '#7dd3fc',
                    muted: '#38bdf8',
                    bright: '#f0f9ff',
                },
                accents: {
                    cyan: '#06b6d4',
                    cyanBright: '#22d3ee',
                    purple: '#0ea5e9',
                    purpleDark: '#0284c7',
                    purpleDarker: '#0369a1',
                    pink: '#38bdf8',
                    pinkBright: '#7dd3fc',
                    pinkHot: '#0891b2',
                    orange: '#0ea5e9',
                    orangeBright: '#38bdf8',
                },
                borders: {
                    primary: '#1e3a5f',
                    secondary: '#2563eb',
                    accent: '#0ea5e9',
                    cyan: '#06b6d4',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#06b6d4',
                },
                syntax: {
                    comment: '#7dd3fc',
                    keyword: '#22d3ee',
                    control: '#0ea5e9',
                    function: '#38bdf8',
                    class: '#0284c7',
                    string: '#5eead4',
                    number: '#fbbf24',
                    variable: '#bae6fd',
                    property: '#0891b2',
                    operator: '#0ea5e9',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(6, 182, 212, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(6, 182, 212, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#f0f9ff',
                    secondary: '#e0f2fe',
                    tertiary: '#bae6fd',
                    surface: '#d1e9f6',
                    elevated: '#e8f5fa',
                    hover: '#bae6fd',
                },
                text: {
                    primary: '#0c4a6e',
                    secondary: '#075985',
                    tertiary: '#0369a1',
                    muted: '#0891b2',
                    bright: '#082f49',
                },
                accents: {
                    cyan: '#0891b2',
                    cyanBright: '#06b6d4',
                    purple: '#0284c7',
                    purpleDark: '#0369a1',
                    purpleDarker: '#075985',
                    pink: '#0ea5e9',
                    pinkBright: '#38bdf8',
                    pinkHot: '#0284c7',
                    orange: '#0891b2',
                    orangeBright: '#06b6d4',
                },
                borders: {
                    primary: '#bae6fd',
                    secondary: '#7dd3fc',
                    accent: '#0ea5e9',
                    cyan: '#06b6d4',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#0891b2',
                    keyword: '#0284c7',
                    control: '#0369a1',
                    function: '#0ea5e9',
                    class: '#0284c7',
                    string: '#059669',
                    number: '#ea580c',
                    variable: '#0c4a6e',
                    property: '#0891b2',
                    operator: '#0284c7',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(6, 182, 212, 0.2)',
                },
                overlays: {
                    bg: 'rgba(8, 145, 178, 0.4)',
                    hover: 'rgba(6, 182, 212, 0.1)',
                },
            },
        },
    },

    'forest-green': {
        name: 'Forest Green',
        slug: 'forest-green',
        description: 'Natural earthy green tones',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a1f0f',
                    secondary: '#0f2817',
                    tertiary: '#051008',
                    surface: '#1a3323',
                    elevated: '#152b1e',
                    hover: '#1e4d2b',
                },
                text: {
                    primary: '#d1fae5',
                    secondary: '#a7f3d0',
                    tertiary: '#6ee7b7',
                    muted: '#34d399',
                    bright: '#ecfdf5',
                },
                accents: {
                    cyan: '#10b981',
                    cyanBright: '#34d399',
                    purple: '#059669',
                    purpleDark: '#047857',
                    purpleDarker: '#065f46',
                    pink: '#6ee7b7',
                    pinkBright: '#a7f3d0',
                    pinkHot: '#059669',
                    orange: '#84cc16',
                    orangeBright: '#a3e635',
                },
                borders: {
                    primary: '#1e4d2b',
                    secondary: '#166534',
                    accent: '#10b981',
                    cyan: '#34d399',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#6ee7b7',
                    keyword: '#34d399',
                    control: '#10b981',
                    function: '#a7f3d0',
                    class: '#059669',
                    string: '#d1fae5',
                    number: '#fbbf24',
                    variable: '#a7f3d0',
                    property: '#34d399',
                    operator: '#10b981',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(16, 185, 129, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(16, 185, 129, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ecfdf5',
                    secondary: '#d1fae5',
                    tertiary: '#a7f3d0',
                    surface: '#d4f4dd',
                    elevated: '#e8f8ec',
                    hover: '#a7f3d0',
                },
                text: {
                    primary: '#064e3b',
                    secondary: '#065f46',
                    tertiary: '#047857',
                    muted: '#059669',
                    bright: '#022c22',
                },
                accents: {
                    cyan: '#059669',
                    cyanBright: '#10b981',
                    purple: '#047857',
                    purpleDark: '#065f46',
                    purpleDarker: '#064e3b',
                    pink: '#10b981',
                    pinkBright: '#34d399',
                    pinkHot: '#047857',
                    orange: '#65a30d',
                    orangeBright: '#84cc16',
                },
                borders: {
                    primary: '#a7f3d0',
                    secondary: '#6ee7b7',
                    accent: '#10b981',
                    cyan: '#34d399',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#059669',
                    keyword: '#047857',
                    control: '#065f46',
                    function: '#10b981',
                    class: '#047857',
                    string: '#064e3b',
                    number: '#ea580c',
                    variable: '#065f46',
                    property: '#059669',
                    operator: '#047857',
                    punctuation: '#ca8a04',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(16, 185, 129, 0.2)',
                },
                overlays: {
                    bg: 'rgba(5, 150, 105, 0.4)',
                    hover: 'rgba(16, 185, 129, 0.1)',
                },
            },
        },
    },

    'sunset-orange': {
        name: 'Sunset Orange',
        slug: 'sunset-orange',
        description: 'Warm sunset-inspired orange and red tones',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#1f0a0a',
                    secondary: '#2d1111',
                    tertiary: '#150505',
                    surface: '#3d1a1a',
                    elevated: '#331414',
                    hover: '#4d2020',
                },
                text: {
                    primary: '#fed7aa',
                    secondary: '#fdba74',
                    tertiary: '#fb923c',
                    muted: '#f97316',
                    bright: '#fff7ed',
                },
                accents: {
                    cyan: '#f97316',
                    cyanBright: '#fb923c',
                    purple: '#ea580c',
                    purpleDark: '#c2410c',
                    purpleDarker: '#9a3412',
                    pink: '#fb923c',
                    pinkBright: '#fdba74',
                    pinkHot: '#ea580c',
                    orange: '#f59e0b',
                    orangeBright: '#fbbf24',
                },
                borders: {
                    primary: '#4d2020',
                    secondary: '#7c2d12',
                    accent: '#f97316',
                    cyan: '#fb923c',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#fdba74',
                    keyword: '#fb923c',
                    control: '#f97316',
                    function: '#fbbf24',
                    class: '#ea580c',
                    string: '#fde047',
                    number: '#fbbf24',
                    variable: '#fed7aa',
                    property: '#fb923c',
                    operator: '#f97316',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(249, 115, 22, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(249, 115, 22, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#fff7ed',
                    secondary: '#ffedd5',
                    tertiary: '#fed7aa',
                    surface: '#fef3e2',
                    elevated: '#fef8f0',
                    hover: '#fed7aa',
                },
                text: {
                    primary: '#7c2d12',
                    secondary: '#9a3412',
                    tertiary: '#c2410c',
                    muted: '#ea580c',
                    bright: '#431407',
                },
                accents: {
                    cyan: '#ea580c',
                    cyanBright: '#f97316',
                    purple: '#c2410c',
                    purpleDark: '#9a3412',
                    purpleDarker: '#7c2d12',
                    pink: '#f97316',
                    pinkBright: '#fb923c',
                    pinkHot: '#c2410c',
                    orange: '#d97706',
                    orangeBright: '#f59e0b',
                },
                borders: {
                    primary: '#fed7aa',
                    secondary: '#fdba74',
                    accent: '#f97316',
                    cyan: '#fb923c',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#ea580c',
                    keyword: '#c2410c',
                    control: '#9a3412',
                    function: '#f97316',
                    class: '#c2410c',
                    string: '#ca8a04',
                    number: '#d97706',
                    variable: '#7c2d12',
                    property: '#ea580c',
                    operator: '#c2410c',
                    punctuation: '#a16207',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(249, 115, 22, 0.2)',
                },
                overlays: {
                    bg: 'rgba(234, 88, 12, 0.4)',
                    hover: 'rgba(249, 115, 22, 0.1)',
                },
            },
        },
    },

    'royal-purple': {
        name: 'Royal Purple',
        slug: 'royal-purple',
        description: 'Elegant purple and magenta theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#1a0a2e',
                    secondary: '#240f3d',
                    tertiary: '#0f051a',
                    surface: '#2e1a4a',
                    elevated: '#261438',
                    hover: '#3d2056',
                },
                text: {
                    primary: '#f3e8ff',
                    secondary: '#e9d5ff',
                    tertiary: '#d8b4fe',
                    muted: '#c084fc',
                    bright: '#faf5ff',
                },
                accents: {
                    cyan: '#a855f7',
                    cyanBright: '#c084fc',
                    purple: '#9333ea',
                    purpleDark: '#7c3aed',
                    purpleDarker: '#6d28d9',
                    pink: '#d946ef',
                    pinkBright: '#e879f9',
                    pinkHot: '#c026d3',
                    orange: '#a855f7',
                    orangeBright: '#c084fc',
                },
                borders: {
                    primary: '#3d2056',
                    secondary: '#6d28d9',
                    accent: '#a855f7',
                    cyan: '#c084fc',
                },
                status: {
                    error: '#f87171',
                    warning: '#fbbf24',
                    success: '#34d399',
                    info: '#22d3ee',
                },
                syntax: {
                    comment: '#d8b4fe',
                    keyword: '#c084fc',
                    control: '#a855f7',
                    function: '#e879f9',
                    class: '#9333ea',
                    string: '#fde047',
                    number: '#fbbf24',
                    variable: '#e9d5ff',
                    property: '#c084fc',
                    operator: '#a855f7',
                    punctuation: '#fde047',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(168, 85, 247, 0.3)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(168, 85, 247, 0.15)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#faf5ff',
                    secondary: '#f3e8ff',
                    tertiary: '#e9d5ff',
                    surface: '#f0e7fa',
                    elevated: '#f7f2fa',
                    hover: '#e9d5ff',
                },
                text: {
                    primary: '#581c87',
                    secondary: '#6d28d9',
                    tertiary: '#7c3aed',
                    muted: '#9333ea',
                    bright: '#3b0764',
                },
                accents: {
                    cyan: '#7c3aed',
                    cyanBright: '#9333ea',
                    purple: '#6d28d9',
                    purpleDark: '#5b21b6',
                    purpleDarker: '#581c87',
                    pink: '#c026d3',
                    pinkBright: '#d946ef',
                    pinkHot: '#a21caf',
                    orange: '#7c3aed',
                    orangeBright: '#9333ea',
                },
                borders: {
                    primary: '#e9d5ff',
                    secondary: '#d8b4fe',
                    accent: '#a855f7',
                    cyan: '#c084fc',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#10b981',
                    info: '#0891b2',
                },
                syntax: {
                    comment: '#9333ea',
                    keyword: '#7c3aed',
                    control: '#6d28d9',
                    function: '#a855f7',
                    class: '#7c3aed',
                    string: '#ca8a04',
                    number: '#ea580c',
                    variable: '#581c87',
                    property: '#9333ea',
                    operator: '#7c3aed',
                    punctuation: '#a16207',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(168, 85, 247, 0.2)',
                },
                overlays: {
                    bg: 'rgba(124, 58, 237, 0.4)',
                    hover: 'rgba(168, 85, 247, 0.1)',
                },
            },
        },
    },

    'monochrome': {
        name: 'Monochrome',
        slug: 'monochrome',
        description: 'Professional grayscale theme',
        isPredefined: true,
        isCustom: false,
        variants: {
            dark: {
                backgrounds: {
                    primary: '#0a0a0a',
                    secondary: '#141414',
                    tertiary: '#050505',
                    surface: '#1f1f1f',
                    elevated: '#1a1a1a',
                    hover: '#2a2a2a',
                },
                text: {
                    primary: '#f5f5f5',
                    secondary: '#e5e5e5',
                    tertiary: '#d4d4d4',
                    muted: '#a3a3a3',
                    bright: '#ffffff',
                },
                accents: {
                    cyan: '#d4d4d4',
                    cyanBright: '#e5e5e5',
                    purple: '#a3a3a3',
                    purpleDark: '#8a8a8a',
                    purpleDarker: '#737373',
                    pink: '#d4d4d4',
                    pinkBright: '#e5e5e5',
                    pinkHot: '#a3a3a3',
                    orange: '#d4d4d4',
                    orangeBright: '#e5e5e5',
                },
                borders: {
                    primary: '#2a2a2a',
                    secondary: '#3f3f46',
                    accent: '#a3a3a3',
                    cyan: '#d4d4d4',
                },
                status: {
                    error: '#ef4444',
                    warning: '#f59e0b',
                    success: '#22c55e',
                    info: '#3b82f6',
                },
                syntax: {
                    comment: '#a3a3a3',
                    keyword: '#e5e5e5',
                    control: '#d4d4d4',
                    function: '#f5f5f5',
                    class: '#e5e5e5',
                    string: '#d4d4d4',
                    number: '#a3a3a3',
                    variable: '#e5e5e5',
                    property: '#d4d4d4',
                    operator: '#a3a3a3',
                    punctuation: '#8a8a8a',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.3)',
                    md: 'rgba(0, 0, 0, 0.5)',
                    lg: 'rgba(212, 212, 212, 0.1)',
                },
                overlays: {
                    bg: 'rgba(0, 0, 0, 0.5)',
                    hover: 'rgba(212, 212, 212, 0.1)',
                },
            },
            light: {
                backgrounds: {
                    primary: '#ffffff',
                    secondary: '#fafafa',
                    tertiary: '#f5f5f5',
                    surface: '#e5e5e5',
                    elevated: '#f0f0f0',
                    hover: '#e5e5e5',
                },
                text: {
                    primary: '#0a0a0a',
                    secondary: '#262626',
                    tertiary: '#404040',
                    muted: '#737373',
                    bright: '#000000',
                },
                accents: {
                    cyan: '#404040',
                    cyanBright: '#262626',
                    purple: '#737373',
                    purpleDark: '#525252',
                    purpleDarker: '#404040',
                    pink: '#404040',
                    pinkBright: '#262626',
                    pinkHot: '#525252',
                    orange: '#404040',
                    orangeBright: '#262626',
                },
                borders: {
                    primary: '#e5e5e5',
                    secondary: '#d4d4d4',
                    accent: '#737373',
                    cyan: '#404040',
                },
                status: {
                    error: '#dc2626',
                    warning: '#f59e0b',
                    success: '#16a34a',
                    info: '#2563eb',
                },
                syntax: {
                    comment: '#737373',
                    keyword: '#262626',
                    control: '#404040',
                    function: '#0a0a0a',
                    class: '#262626',
                    string: '#404040',
                    number: '#737373',
                    variable: '#262626',
                    property: '#404040',
                    operator: '#737373',
                    punctuation: '#a3a3a3',
                },
                shadows: {
                    sm: 'rgba(0, 0, 0, 0.1)',
                    md: 'rgba(0, 0, 0, 0.15)',
                    lg: 'rgba(64, 64, 64, 0.1)',
                },
                overlays: {
                    bg: 'rgba(10, 10, 10, 0.4)',
                    hover: 'rgba(64, 64, 64, 0.1)',
                },
            },
        },
    },
};

// Helper function to get all theme names
export const getThemeNames = () => Object.keys(themePresets);

// Helper function to get a specific theme
export const getTheme = (slug) => themePresets[slug];

// Helper function to check if a theme is predefined
export const isPredefinedTheme = (slug) => !!themePresets[slug];
